name: Docker build Practice


#workflow-dispatch is used for manuall run because for testing we dont need to push our code again and again after testing completed we can use
#on:-push-main branch something like that
# on:
#   workflow_dispatch:

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read          #Workflow can read repository
  packages: write         #Workflow can upload Docker package/image
  #Without the appropriate package permission, the push can fail with a permission/authorization error.

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4  # means GitHub Actions will check out the repository code onto the GitHub runner.

      - name: Setup .NET
        uses: actions/setup-dotnet@v4  #GitHub runner, install/setup the .NET 8 SDK so that I can run dotnet restore, dotnet build, and dotnet test."It does not build your application yet.It's only preparing the .NET environment.
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore  #It reads your .sln / .csproj files and downloads the NuGet packages your application needs. We are intentionally putting Restore before Docker Build.

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3  #This prepares the Docker building environment on the Ubuntu runner.It is essentially saying: "GitHub runner, prepare Docker Buildx so I can build my Docker image."
      
      - name: Build application
        run: dotnet build --no-restore --configuration   #So there is no reason for dotnet build to restore the packages again.
      

      - name: Publish application
        run: dotnet publish --no-build --configuration Release --output ./publish
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io                     #GitHub Container Registry.
          username: ${{ github.actor }}         #the GitHub user who triggered the workflow.
          password: ${{ secrets.GITHUB_TOKEN }}  #temporary token automatically provided to the workflow.

      - name: Get Docker version
        id: version
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Docker version: $VERSION"


        #GITHUB_REF_NAME = v1.0.0
        #VERSION="${GITHUB_REF_NAME#v}" = VERSION=1.0.0
        #echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        #${{ steps.version.outputs.version }}

      - name: build docker images
        uses: docker/build-push-action@v6   # Build Docker image  +  Optionally push Docker image. Pushing is depending open the option true or false.
        with:
          context: .
          file: ./src/OrderAPIService/Dockerfile
          push: true

          cache-from: type=gha #Before building, check whether GitHub Actions already has Docker build layers that can be reused.
          cache-to: type=gha,mode=max #After building, save the Docker build cache in GitHub Actions' cache storage

          #tags: orderapi:1.0.0
          #tags: ghcr.io/${{ github.repository_owner }}/orderapi:1.0.0
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}


# Now if someone asks:  "Which Docker image is production version 1.0.1?"  
# You can directly use: orderapi:1.0.1

# If someone asks: "Which exact source commit created this image?"
#You can use:  orderapi:c2c0c2b0bf4c478e1ce50f640e7dd069ee67a54a 
#And: 
#orderapi:latest
#always points to the latest image published by this workflow.