# Project Name is OrderAPIService and SolutionName is RabbitMQPractice like that GitHubWorkflow Name is RabbitMQ CI Pipeline
# where it is show this name?:- Suupose we push our code GitHub Execute the workflow. on Github we see this name.
# name is not Mandaotory.
name: RabbitMQ CI Pipeline

# For e.g. Think about your house. You have a doorbell.
# When someone presses the bell...  Door Bell Pressed-> Bell Rings.
# If nobody presses the bell... Nothing Happens
# The bell needs an event to occur.
# GitHub Actions works exactly the same way. A workflow does not run by itself. It waits for an event.

# on (Means Tell me which event should start for this workflow.")
# Event (An event is simply something that happens inside GitHub.
#        for e.g.
                #1. Developer pushes code
                #2. Developer creates Pull Request
                #3. Developer creates Release
                #4. Every night at 2 AM
                #5. Someone clicks Run Workflow
                # All of these are events.)
# Whenever someone pushes code to this repository, start this workflow.


# Let's understand using your project
# You modified  OrderController.cs
# Then you execute
# git add .
# git commit -m "Added retry logic"
# git push

# What happens? Internally:

# Your Laptop-->  git push--> GitHub receives commit --> GitHub checks -> .github/workflows--> It finds --> dotnet.yml --> It opens it. Reads

# on:
#   push:
# GitHub says: "A push just happened." --> ✅ Condition matched. --> Now the workflow starts.
on:
  push:
    branches:
      - main


#
# What is jobs:? Let's use a real-life example. Suppose your manager says:  "Build a house."  He doesn't tell one person to do everything. Instead, the work is divided.
# House Project
#     │
#     ├── Civil Team
#     ├── Electrical Team
#     ├── Plumbing Team
#     └── Painting Team

#Each team has one responsibility. GitHub Actions works the same way.

# Our entire workflow is:  RabbitMQ CI Pipeline Inside it, we need different kinds of work. For example:

# RabbitMQ CI Pipeline
#         │
#         ├── Build Project
#         ├── Run Tests
#         ├── Security Scan
#         └── Deploy

# Each of these is called a Job. Why do we write jobs:?  The keyword

# jobs: tells GitHub:  "From here onwards, I'm defining the work that needs to be done." Think of it as a container.

# jobs
# │
# ├── build
# ├── test
# └── deploy

# What do you mean by Build? Many beginners think build is a GitHub keyword. But It is not. This is very important. build is just a name.
# We could have written: rabbitmq-build:    jagannath-job:
# GitHub doesn't care.  It simply treats it as the Job ID. However, in real projects we use meaningful names like: build, test, deploy, publish
## Notice that one workflow can have many jobs. For our first workflow, we'll keep it simple. Only one job:
# "jobs defines the collection of work that the workflow will execute. Each job is an independent unit of work and contains one or more steps."
jobs:
  build:


# GitHub says: "I have one job named build."  At this point, GitHub knows the job exists. But it still doesn't know:

# Which operating system to use ❌
# Which machine to use ❌
# Which commands to execute ❌

# We'll define those in the next steps.



#GitHub creates a temporary machine, called a Runner.
#So every time you push: GitHub creates a fresh Ubuntu VM.  Downloads your repository.   Executes your workflow. Deletes the VM after the workflow finishes. Nothing remains on that machine after the run.
# why Ubuntu ? because it fast. like Ubuntu any other runner are there ? yes -> windows-latest,  macos-latest
#Suppose you push your RabbitMQ project. GitHub internally does something like this:
# Step 1  Create Ubuntu Runner
# Step 2  Download your repository
# Step 3  Install .NET SDK
# Step 4  Build the project
# Step 5  Run tests
# Step 6  Delete the Runner
    runs-on: ubuntu-latest

# Imagine you're building a .NET application. Instead of writing your own JSON serializer, you use: using System.Text.Json;
#                                             instead of writing your own logging framework, you use: using Microsoft.Extensions.Logging;
# Just like NuGet packages have versions:  Newtonsoft.Json 13.0.3
# GitHub Actions also have versions. actions/checkout@v4 means: Use version 4 of the Checkout Action.

# actions  :- This is the owner (GitHub).
# checkout :- This is the action name.
# @v4      :- This is the version.

# A job is made up of one or more steps.
# Steps execute sequentially (one after another).
# If one step fails, the remaining steps are skipped unless configured otherwise.

    steps:
     # Checkout	        Downloads your source code to the runner 
      - name: Checkout source code
        uses: actions/checkout@v4

      # Setup .NET	      Installs the .NET 8 SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      # Restore	          Downloads all NuGet packages
      - name: Restore dependencies
        run: dotnet restore RabbitMQPractice.slnx

      # Build	            Compiles your solution
      - name: Build solution
        run: dotnet build RabbitMQPractice.slnx --configuration Release --no-restore

      
      
      # # Test	            Runs unit tests (we'll add tests later)
      # - name: Run tests
      #   run: dotnet test RabbitMQPractice.slnx --no-build --verbosity normal

      # Publish	          Creates the deployable application
      - name: Publish Order API
        run: dotnet publish src/OrderAPIService/OrderAPIService.csproj --configuration Release --output ./publish --no-build

      # Upload            Artifact	Stores the published output in GitHub Actions
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrderAPIService
          path: ./publish

# What each step does
# Step	                  Purpose
# Checkout	        Downloads your source code to the runner
# Setup .NET	      Installs the .NET 8 SDK
# Restore	          Downloads all NuGet packages
# Build	            Compiles your solution
# Test	            Runs unit tests (we'll add tests later)
# Publish	          Creates the deployable application
# Upload            Artifact	Stores the published output in GitHub Actions

# Debug :- Used while developing
# ✔ Easier debugging
# ✔ More debug information
# ✔ Not optimized

# Release:-Used for production

# ✔ Optimized
# ✔ Faster
# ✔ Smaller output

# Why do we use --no-restore?
# Because the workflow has already executed dotnet restore. Using --no-restore avoids repeating the restore step, reducing build time.